### LOGIN
POST http://localhost:3000/auth/login
content-type: application/json

{
    "email": "test_user@gmail.com",
    "password": "password"
}

### REGISTER
POST http://localhost:3000/users
content-type: application/json

{
    "username": "test_user",
    "email": "test_user@gmail.com",
    "password": "password"
}

### YOUTUBE SEARCH
GET http://localhost:3000/youtube/search?search_query=test
content-type: application/json

### YOUTUBE VIDEO LICENSE
GET http://localhost:3000/youtube/video?video_id=LOhfqjmasi0
content-type: application/json